[mail function]
SMTP = smtp.gmail.com
smtp_port = 587
sendmail_from = hersafarenquiry@gmail.com
sendmail_path = "\"C:\xampp\sendmail\sendmail.exe\" -t"
smtp_server=smtp.gmail.com
smtp_port=587
smtp_ssl=auto
error_logfile=error.log
smtp_username=hersafarenquiry@gmail.com
smtp_password=gkwy mmfa yuwy bzss
session.cookie_secure = 1
session.use_cookies = 1
session.use_only_cookies = 1
